### ISSUE TITLE
Some info for readme edits

### ISSUE THREAD

**Issue by ColinTNMP** [IntenseBattle2/IntelligentBinaryMonsters-Elements#1]
Unfortunately, it seems readme doesn't add a new line properly unless you add "\<br/\>" to the end of a line. Please keep this in mind when writing documents. This ISN'T needed for code, so don't add it unless you want to screw up the code!

Also, if you want to add to type \<br/\> without making a newline, you have to use \\\<br/\\\> instead -- escaping characters works here as well!

**Comment by Zachman9841** [comment]
Are you going to close this Issue soon? Or is it for the public to see? 📧
